/*  Find the Difference
Solved
Easy
Topics
premium lock icon
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.*/

class Solution {
    public char findTheDifference(String s, String t) {
        int sSum=0;
        int tSum=0;
        for(char ch : s.toCharArray()){
  sSum = sSum+ch;
        }

        for(char ch : t.toCharArray()){
  tSum = tSum+ch;
        }

        return (char)(tSum-sSum);
    }
}
